# dependency_stage
FROM node:20-alpine AS deps
WORKDIR /myremix_deps_dir
COPY package*.json ./
RUN npm install

# run_stage
FROM node:20-alpine
WORKDIR /myremix_dir
COPY --from=deps "/myremix_deps_dir/node_modules" "./node_modules"
COPY . .
CMD [ "npm", "run", "dev" ]
