# dependency_stage
FROM node:20-alpine as deps
WORKDIR /myreact_dir
COPY package.json .
RUN yarn

# build_stage
FROM deps as build
WORKDIR /myreact_dir
COPY . .
RUN yarn run build

# run_stage
FROM nginx:1.25.4-alpine as run_stage
COPY --from=build /myreact_dir/.nginx/nginx.conf /etc/nginx/conf.d/default.conf
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build /myreact_dir/dist .
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]