AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  TriAwsLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: tri-aws-lambda
      Handler: com.learnaws.LambdaHandler::handleRequest
      Runtime: java17
      CodeUri: s3://tri-aws-bucket/6e7a209e82fe79fae3b4be9e643f31b2
      MemorySize: 512
      Timeout: 30
      Role: arn:aws:iam::033237493133:role/tri-aws-role-full-lambda
      Environment:
        Variables:
          BUCKET_NAME: tri-aws-bucket
          QUEUE_URL: https://sqs.us-east-1.amazonaws.com/033237493133/tri-aws-queue
    Metadata:
      SamResourceId: TriAwsLambdaFunction
