spring:
  application:
    name: Donglao_app
  flyway:
    enabled: false
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://${MY_POSTGRES_HOST:localhost}:${MY_POSTGRES_PORT:5432}/${MY_POSTGRES_DB:postgres}
    username: ${MY_POSTGRES_USER:postgres}
    password: ${MY_POSTGRES_PASSWORD:123123123}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: simple
  # data:
  #   redis:
  #     host: ${MY_REDIS_HOST}
  #     port: ${MY_REDIS_PORT}
  #     password: ${MY_REDIS_PASSWORD}
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
