# deps_stage
FROM maven:3.9.6-eclipse-temurin-17-alpine AS deps_stage
WORKDIR /mybackend_build_dir
COPY pom.xml .
COPY .mvn .mvn
RUN mvn dependency:go-offline


# This layer will be rebuilt when source code changes
FROM deps_stage AS build_stage
COPY src src

# run_stage
FROM build_stage
WORKDIR /mybackend_dir
COPY --from=build_stage "/mybackend_build_dir" "/mybackend_dir"
CMD [ "mvn", "spring-boot:run" ]