app:
  analyze-config:
    - filename: 'some_mybatis_file_1.xml'
      methodsToFind:
        - 'update01'
        - 'select01'
        - 'select02'
        - 'select03'
        - 'insert01'
    - filename: 'some_mybatis_file_2.xml'
      methodsToFind:
        - 'update01'
        - 'select01'
        - 'select03'
        - 'updateGeneric'
