app:
  analyze-config:
    - filename: 'mybatis_1.xml'
      methodsToFind:
        - 'select01'
        - 'select02'
        - 'select03'
        - 'insert01'
        - 'update01'
    - filename: 'mybatis_2.xml'
      methodsToFind:
        - 'update01'
        - 'update02'
        - 'select01'
        - 'select02'
