# dependency_stage
FROM node:20-alpine as deps
WORKDIR /myreact_dir
COPY package.json .
RUN npm install

# build_stage
FROM deps as build
WORKDIR /myreact_dir
COPY . .
RUN npm run build

# run_stage
FROM nginx:stable-alpine as run_stage
COPY --from=build "/myreact_dir/.nginx/nginx.conf" "/etc/ngin/conf.d/default.conf"
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build "/myreact_dir/dist" .
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]


