# dependency_stage
FROM oven/bun:1.1.4-alpine AS deps
WORKDIR /myreact_dep_dir
COPY package.json bun.lockb ./
RUN bun install

# build_stage
FROM oven/bun:1.1.4-alpine
WORKDIR /myreact_dir
COPY --from=deps "/myreact_dep_dir/node_modules" "./node_modules"
COPY . .
ENTRYPOINT [ "bun", "run", "dev" ]


