# dependency_stage
FROM node:20-alpine as deps
WORKDIR /myreact_dir
COPY package.json .
RUN npm install

# build_stage
FROM deps as build
WORKDIR /myreact_dir
COPY . .
RUN npm run build

# run_stage
FROM nginx:stable-alpine as run_stage
WORKDIR /usr/share/nginx/html
COPY --from=build "/myreact_dir/dist" .
RUN rm -rf /etc/nginx/conf.d/default.conf
COPY --from=build "/myreact_dir/.nginx/nginx.conf" "/etc/nginx/conf.d/default.conf"
EXPOSE 80
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]


