# dependency_stage
FROM node:22.6.0-alpine3.19 AS deps
WORKDIR /myreact_dep_dir
COPY package.json ./
RUN npm install

# build_stage
FROM node:20.16.0-alpine3.20
WORKDIR /myreact_dir
COPY --from=deps "/myreact_dep_dir/node_modules" "./node_modules"
COPY . .
ENTRYPOINT [ "npm", "run", "dev" ]


