spring:
  application:
    name: learn-mcp
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
  ai:
    mcp:
      server:
        name: my-super-mcp-server
        version: 0.0.1
        enabled: true
        type: sync
        sse-endpoint: /my-sse
        sse-message-endpoint: /my-sse-messages
        base-url: /api/v1/mcp 

logging:
  pattern:
    console:
  file:
    name: logs/learn-mcp.log
