version: '3.8'
services:
  fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile.production
    container_name: vite-remix
    ports:
      - "3000:3000"
    tty: true
networks:
  frontend:
  backend:
volumes:
  db-data:
