spring:
  application:
    name: Donglao_app
  flyway:
    enabled: true  # Enable Flyway
    baseline-on-migrate: true  # Baseline on migrate
    # locations: classpath:db/migration
    # url: jdbc:postgresql://${MY_POSTGRES_HOST}:${MY_POSTGRES_PORT}/${MY_POSTGRES_DB}
    # user: ${MY_POSTGRES_USER}
    # password: ${MY_POSTGRES_PASSWORD}
    # schemas: public
  datasource:
    url: jdbc:postgresql://${MY_POSTGRES_HOST:localhost}:${MY_POSTGRES_PORT:5432}/${MY_POSTGRES_DB:postgres}
    username: ${MY_POSTGRES_USER:postgres}
    password: ${MY_POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate  # Disable Hibernate's automatic DDL generation
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      host: ${MY_REDIS_HOST}
      port: ${MY_REDIS_PORT}
      password: ${MY_REDIS_PASSWORD}
    mongodb:
      username: ${MY_MONGO_USER}
      password: ${MY_MONGO_PASSWORD}
      host: ${MY_MONGO_HOST}
      port: ${MY_MONGO_PORT}
      database: ${MY_MONGO_DB}
      authentication-database: admin
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html